### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [Titef84/grid-template-init-project#1]
1)

Ваша работа содержит невалидный код (невалидный - означает несоответствие стандартам HTML, другими словами - код с критическими ошибками).
Все файлы проекта, без исключения, должны проходить валидацию.
HTML валидатор... https://validator.w3.org/#validate_by_input
  CSS валидатор... https://jigsaw.w3.org/css-validator/#validate_by_upload

![image](https://user-images.githubusercontent.com/8464662/153467060-c1ef6264-fef0-4622-9391-05a41adda53c.png)

2)

Ваша работа содержит невалидный код (невалидный - означает несоответствие стандартам CSS, другими словами - код с критическими ошибками).
Все файлы проекта, без исключения, должны проходить валидацию.
HTML валидатор... https://validator.w3.org/#validate_by_input
  CSS валидатор... https://jigsaw.w3.org/css-validator/#validate_by_upload

![image](https://user-images.githubusercontent.com/8464662/153467123-fe2c8a2e-d238-44d1-83b8-c06eddbdd9b5.png)

3)
изорражение отсуствует
![image](https://user-images.githubusercontent.com/8464662/153467220-cf53e453-03ee-4f23-9e95-7844164c0d97.png)

**Comment by Titef84** [comment]
Ошибки просмотрел и исправил

**Comment by Alecto** [comment]
4)
Внешний вид заполнителей и активного элемента не соответствует макету.
![image](https://user-images.githubusercontent.com/8464662/153656597-e79b8afa-62ad-48e8-bb1e-69cd62ed4dde.png)


5)
обратная анимация отсуствует
![image](https://user-images.githubusercontent.com/8464662/153656668-7720f338-a19c-47af-9e79-6332de32cfce.png)


6)
Некорректный вид элемента.
![image](https://user-images.githubusercontent.com/8464662/153656766-a8cc1110-6ac4-41a0-aa37-ce5d6ed7c39d.png)

**Comment by Titef84** [comment]
Внес изменения по замечаниям
https://github.com/Titef84/grid-template-init-project
https://titef84.github.io/grid-template-init-project/

пт, 11 февр. 2022 г. в 21:28, Andrey ***@***.***>:

**Comment by Alecto** [comment]
4, 5 - не исправлено

**Comment by Titef84** [comment]
Исправил
https://github.com/Titef84/grid-template-init-project
https://titef84.github.io/grid-template-init-project/

**Comment by Alecto** [comment]
Сообщите пожалуйста название (день + время) группы + ваши имя фамилию.
В переписке эта информация отсуствует.

пн, 14 лют. 2022 р. о 22:03 Titef84 ***@***.***> пише:

**Comment by Titef84** [comment]
SkillUp FrontEnd. Проходец Александр, вт/чт 20-00
